// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAoNUCiXFc3NvGFZUR6ff7YXGEHvyxZlU',
    appId: '1:83609779980:web:2ffb79bd3edaf9782c1329',
    messagingSenderId: '83609779980',
    projectId: 'chatapp-6fe33',
    authDomain: 'chatapp-6fe33.firebaseapp.com',
    storageBucket: 'chatapp-6fe33.appspot.com',
    measurementId: 'G-FG86JQSZYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2LHJv06g978XcEljY65qlc4_hDh5pSBI',
    appId: '1:83609779980:android:50386b08d60290282c1329',
    messagingSenderId: '83609779980',
    projectId: 'chatapp-6fe33',
    storageBucket: 'chatapp-6fe33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYmeYhyJPBVFoRiLG11jhFEZL9aR1C_mU',
    appId: '1:83609779980:ios:12b7b573131b2bb52c1329',
    messagingSenderId: '83609779980',
    projectId: 'chatapp-6fe33',
    storageBucket: 'chatapp-6fe33.appspot.com',
    iosClientId: '83609779980-pms3j7b8apk0lmm66ucocpg0v2eeeahd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYmeYhyJPBVFoRiLG11jhFEZL9aR1C_mU',
    appId: '1:83609779980:ios:12b7b573131b2bb52c1329',
    messagingSenderId: '83609779980',
    projectId: 'chatapp-6fe33',
    storageBucket: 'chatapp-6fe33.appspot.com',
    iosClientId: '83609779980-pms3j7b8apk0lmm66ucocpg0v2eeeahd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
